# Generated by Django 5.1.5 on 2025-02-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cheese',
            field=models.CharField(choices=[('MOZ', 'Mozzarella'), ('VEG', 'Vegan'), ('LF', 'Low Fat')], default='MOZ', max_length=3),
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(choices=[('TOM', 'Tomato'), ('BBQ', 'BBQ')], default='TOM', max_length=3),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('N', 'Normal'), ('TH', 'Thick'), ('TN', 'Thin'), ('GF', 'Gluten Free')], default='N', max_length=2),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
