# Generated by Django 5.1.5 on 2025-02-11 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasystem', '0002_pizza_cheese_pizza_sauce_alter_pizza_crust_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Chicken', 'Chicken'), ('Ham', 'Ham'), ('Pineapple', 'Pineapple'), ('Peppers', 'Peppers'), ('Mushrooms', 'Mushrooms'), ('Onions', 'Onions')], default='Pepperoni', max_length=15),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('paymentinfo', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
