# Generated by Django 5.1.5 on 2025-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasystem', '0003_alter_pizza_user_alter_pizza_toppings_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paymentinfo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_card_cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_card_expiry',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
